# Based on https://github.com/conda-forge/vtk-feedstock/blob/e42b7caafd650106eb1559df35f792f286b0a4d5/recipe/meta.yaml
{% set version = "7.1.1" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}

package:
  name: vtk
  version: {{ version }}

source:
  url: http://www.vtk.org/files/release/{{ minor_version }}/VTK-{{ version }}.tar.gz
  fn:  VTK-{{ version }}.tar.gz
  sha256: 2d5cdd048540144d821715c718932591418bb48f5b6bb19becdae62339efa75a

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
  skip: True  # [osx or py27]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.7.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.7.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - Korijn
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
