{% set version = "9.0.0.rc1" %}
{% set build = 4 %}

package:
  name: vtk
  version: {{ version }}

source:
  path: ../test

build:
  number: {{ build }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - ninja

  host:
    - zlib
    - libpng

  run:
    - zlib
    - libpng

about:
  home: http://www.vtk.org/
  license: BSD-3-Clause
  license_file: Copyright.txt
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
    - marcelotrevisani
    - xylar
    - muryanto1
    - downiec
    - jasonb5
