{% set version = "7.1.0" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}

package:
  name: vtk
  version: {{ version }}

source:
  url: http://www.vtk.org/files/release/{{ minor_version }}/VTK-{{ version }}.tar.gz
  fn:  VTK-{{ version }}.tar.gz
  sha256: 5f3ea001204d4f714be972a810a62c0f2277fbb9d8d2f8df39562988ca37497a
  patches:
    # This patch fix the issue: https://gitlab.kitware.com/vtk/vtk/issues/16920,
    # causing a segmentation fault during Mayavi installation.
    # It will be available in VTK 7.1.1, and is a backport of the commit:
    # https://gitlab.kitware.com/vtk/vtk/commit/714d8e6071d685e34bb21a2fde7b67811135e582
    # Patch was created from VTK Git repo with: `git format-patch -1 714d8e6`
    - 0001-16920-Mark-vtkPainterCommunicator-as-not-wrappable.patch

build:
  number: 5
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
  skip: True  # [py3k]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.7.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.7.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - Korijn
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
