# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "9.5.2"
  build: 7
  minor_version: ${{ (version | split('.'))[:2] | join('.') }}

recipe:
  name: vtk-split
  version: ${{ version }}

source:
  url: http://www.vtk.org/files/release/${{ minor_version }}/VTK-${{ version }}.tar.gz
  sha256: cee64b98d270ff7302daf1ef13458dff5d5ac1ecb45d47723835f7f7d562c989
  patches:
    - if: win
      then:
        - patches/fix-threads-windows.patch
    # https://github.com/conda-forge/vtk-feedstock/pull/282
    # https://gitlab.kitware.com/vtk/vtk/-/issues/18365#note_1079278
    # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9987
      else:
        - patches/9987_try_except_python_import.patch
    - patches/expat_use_pkgconfig_version.patch
    - patches/ioss_fix_fmt12.patch

build:
  number: ${{ build }}

outputs:
  - package:
      name: vtk-base
    build:
      script:
        - if: not win
          then: ${RECIPE_DIR}/build-base.sh
          else: "%RECIPE_DIR%\\bld-base.bat"
      post_process:
        - if: unix
          then:
            - files:
                - "*.cmake"
              regex: '([^;\s"]+/sysroot)'
              replacement: "$${CONDA_BUILD_SYSROOT}"
        - if: osx
          then:
            - files:
                - "*.cmake"
              regex: '([^;\s"]+/MacOSX\d*\.?\d*\.sdk)'
              replacement: "$${CONDA_BUILD_SYSROOT}"
    requirements:
      build:
        - ${{ compiler("cxx") }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - qt6-main
      host:
        - python
        - zlib
        - liblzma-devel
        - freetype
        - hdf5
        - hdf5 * nompi_*
        - libxml2-devel
        - libpng
        - libjpeg-turbo
        - libtiff
        - jsoncpp
        - expat
        - fmt
        - tbb
        - tbb-devel
        - libnetcdf
        - libnetcdf * nompi_*
        - lz4-c
        # TODO: Someday we should add Vulkan once it can be found in conda-forge
        # These packages are not CDT to help with compat with other builds
        # (e.g., tensorflow, qt-main), e.g.
        # https://github.com/conda-forge/qt-main-feedstock/blob/2b166b35e9e1a2d897640ac28ae4b00491d9e310/recipe/meta.yaml#L134-L138
        - if: linux
          then:
            - libgl-devel
            - libegl-devel
            - libglvnd-devel
            - libglx-devel
            - libglu
            - libopengl-devel
            - libxcb
            - libxkbfile
            - libuuid
            # still missing: Xaccessrules Xxf86misc, xcb_errors, xcb_xrm
            - xorg-xproto
            - xorg-libxcursor
            - xorg-libxft
            - xorg-libxt
            - xorg-libxv
            - xorg-libxext
            - xorg-libxres
            - xorg-libxaw
            - xorg-libxinerama
            - xorg-libxpm
            - xorg-libxmu
            - xorg-libxxf86vm
            - xorg-libx11
            - xorg-xf86vidmodeproto
        - libboost-headers
        - ffmpeg
        - ffmpeg * lgpl_*
        - utfcpp
        - eigen
        - cli11
        - double-conversion
        - pugixml
        - glad2-cmake
        - glad2
        - libogg
        - libtheora
        - nlohmann_json
        - proj
        - sqlite
        - viskores
        # Until this is solved:
        # https://gitlab.kitware.com/vtk/vtk/-/issues/19561
        # we use the internal one in build-base.sh
        - if: not osx
          then:
            - gl2ps
        - if: not ppc64le
          then:
            - qt6-main
      run:
        - python
        - utfcpp
        - nlohmann_json
        - cli11
        - loguru
        - numpy
        - wslink
        - matplotlib-base >=2.0.0
      run_constraints:
        - ${{ pin_compatible('libboost-headers', upper_bound='x.x') }}
      run_exports:
        - ${{ pin_subpackage('vtk-base', upper_bound='x.x.x') }}
      ignore_run_exports:
        by_name:
          - if: not win
            then:
              - ffmpeg
          # Found via inspection of the conda-forge logs, hopefully okay to ignore:
          - if: linux
            then:
              - xorg-libxext
              - xorg-libxxf86vm
              - xorg-libxft
              - xorg-libxt
              - xorg-libxmu
              - libxcb
              - libglvd
              - libuuid
              - xorg-libxv
              - libgl
              - xorg-libxpm
              - libegl
              - xorg-libxinerama
    tests:
      - python:
          imports:
            - vtk
            - vtk.vtkChartsCore
            - vtk.vtkCommonCore
            - vtk.vtkFiltersCore
            - vtk.vtkFiltersGeneric
            - vtk.vtkGeovisCore
            - vtk.vtkFiltersHybrid
            - vtk.vtkIOCore
            - vtk.vtkImagingCore
            - vtk.vtkInfovisCore
            - vtk.vtkRenderingCore
            - vtk.vtkViewsCore
            - vtk.vtkRenderingVolume
            - vtk.vtkInteractionWidgets
            - vtk.vtkWebGLExporter
            - vtkmodules
            - vtkmodules.vtkChartsCore
            - vtkmodules.vtkCommonCore
            - vtkmodules.vtkFiltersCore
            - vtkmodules.vtkFiltersGeneric
            - vtkmodules.vtkGeovisCore
            - vtkmodules.vtkFiltersHybrid
            - vtkmodules.vtkIOCore
            - vtkmodules.vtkImagingCore
            - vtkmodules.vtkInfovisCore
            - vtkmodules.vtkRenderingCore
            - vtkmodules.vtkRenderingMatplotlib
            - vtkmodules.vtkViewsCore
            - vtkmodules.vtkRenderingQt
            - vtkmodules.vtkRenderingVolume
            - vtkmodules.vtkInteractionWidgets
            - vtkmodules.vtkWebCore
            - vtkmodules.web
            - vtkmodules.web.utils
            - if: not win
              then:
                - vtkmodules.tk.vtkTkRenderWidget
      - script:
          # We test the import vtkmodules.qt.QVTKRenderWindowInteractor here as it requires
          # the pyisde6 optional dependency, that we can't add as a dependency in the python tests section
          - if: not ppc64le
            then:
              - python -c "import vtkmodules.qt.QVTKRenderWindowInteractor"
          - if: unix
            then:
              - test $(pip list | grep vtk | tr -s " " | grep $PKG_VERSION | wc -l) -eq 1
          - if: win
            then:
              - pip list | findstr "vtk"
          # Ideally here we would do:
          # {% for vtk_lib in ["vtkGUISupportQt", "vtkRenderingQt"] %}
          # ...
          # {% endfor %}
          # But it breaks the linter :( so we do it manually
              - if not exist %PREFIX%\\Library\\lib\\vtkGUISupportQt-${{ minor_version }}.lib exit 1
              - if not exist %PREFIX%\\Library\\bin\\vtkGUISupportQt-${{ minor_version }}.dll exit 1
              - if not exist %PREFIX%\\Library\\lib\\vtkRenderingQt-${{ minor_version }}.lib exit 1
              - if not exist %PREFIX%\\Library\\bin\\vtkRenderingQt-${{ minor_version }}.dll exit 1
            else:
              - test -f $PREFIX/lib/libvtkGUISupportQt-${{ minor_version }}${SHLIB_EXT}
              - test -f $PREFIX/lib/libvtkRenderingQt-${{ minor_version }}${SHLIB_EXT}
        requirements:
          run:
            - pip
            - setuptools
            - if: not ppc64le
              then:
                - pyside6

  - package:
      name: vtk-io-ffmpeg
    build:
      skip:
        - win
      script:
        - if: not win
          then: ${RECIPE_DIR}/build-io-ffmpeg.sh
          else: exit 1
    requirements:
      build: []
      host:
        # We use python and ffmpeg here in the host section so that conda build
        # uses the global pinnings and ensures compatibility, as both ffmpeg and python
        # are dependency of the package
        - python
        - ffmpeg
      run:
        - ${{ pin_subpackage("vtk-base", exact=true) }}
        - ffmpeg
      run_exports:
        - ${{ pin_subpackage('vtk-io-ffmpeg', upper_bound='x.x.x') }}
    tests:
      - python:
          imports:
            - vtk.vtkIOFFMPEG

  - package:
      name: vtk
    build: {}
    requirements:
      build: []
      host:
        - python
      run:
        # The pin_subpackage is not exact to avoid issues like https://github.com/conda-forge/vtk-feedstock/issues/347
        # and https://github.com/conda-forge/vtk-feedstock/issues/372
        - ${{ pin_subpackage("vtk-base", upper_bound='x.x.x') }}
        - if: not win
          then:
            - ${{ pin_subpackage("vtk-io-ffmpeg", upper_bound='x.x.x') }}
        # The following dependencies are here to make sure that find_package(VTK) works fine, they could be moved to vtk-devel if that is ever created
        - if: linux
          then:
            - libgl-devel
            - libopengl-devel
        - libboost-devel
        - liblzma-devel
        - tbb-devel
        - eigen
        - expat
      run_exports:
        - ${{ pin_subpackage('vtk-base', upper_bound='x.x.x') }}
    tests:
      - python:
          imports:
            - vtk
      - if: not win
        then:
          - python:
              imports:
                - vtk.vtkIOFFMPEG
      - script:
          # uncomment once we fix test_vtk.py, see https://github.com/conda-forge/vtk-feedstock/issues/383#issuecomment-2890722669
          # - python test_vtk.py
          - cmake-package-check VTK
        requirements:
          run:
            - pip
            - setuptools
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
            - libxml2-devel

about:
  homepage: http://www.vtk.org/
  license: BSD-3-Clause
  license_file:
    - Copyright.txt
    - vendored-fast_float-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/master/ThirdParty/fast_float/vtkfast_float/LICENSE-MIT
    - vendored-libharu-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/master/ThirdParty/libharu/vtklibharu/LICENSE
    - vendored-loguru-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/v9.4.1/ThirdParty/loguru/vtkloguru/LICENSE
    - vendored-pegtl-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/master/ThirdParty/pegtl/vtkpegtl/LICENSE
    - vendored-exprtk-license.txt  # https://github.com/conda-forge/exprtk-feedstock/blob/main/license.txt
    - vendored-cgns-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/master/ThirdParty/cgns/vtkcgns/license.txt
    - vendored-ioss-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/master/ThirdParty/ioss/vtkioss/COPYRIGHT
    - vendored-token-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/master/ThirdParty/token/vtktoken/license.md
    - vendored-verdict-license.txt  # https://gitlab.kitware.com/vtk/vtk/-/blob/master/ThirdParty/verdict/vtkverdict/LICENSE
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, modeling, image processing, volume rendering, scientific visualization, and information visualization.
  repository: https://gitlab.kitware.com/vtk/vtk
  documentation: https://vtk.org/documentation

extra:
  feedstock-name: vtk
  recipe-maintainers:
    - traversaro
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
    - marcelotrevisani
    - downiec
    - jasonb5
    - matthiasdiener
    - basnijholt
    - Tobias-Fischer
    - vicentebolea
