appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
travis:
  secure: {BINSTAR_TOKEN: VlKBEOnqh0LecfYUFAfokeEoNFTkiMbRttR7iFO6tMEUzPkmAjc4HgudeHtThy4vW7F3HCIPYRX9HioAGacXJZc7dLa3xmbktrsOXMJPJTtDElL6WhwjckBorPStwPf9YexEz6TNI18G2q0y+XyM9eS4fd/gkugaMlP4wI1ne94ghGt03N3DHO+eosDEa08H+gnOqr7sQMUU6Oe+p/sm/Nv5rznOwph55Rc3S8cDcGT3usqvKqWzK+2Y7a+uPK9AsYMhO6E1+k3o9NjjPJKV95OV5neVlSocuwiOTQml/FnVQXHnlgpzL5hFF1jNWckWr0bW42jwsk+49XMfjRF/+73nj191S+ND2WmRyK6+DrwodXoGNcFzN/MwwCvXT0RBSzdMpXHqVF6qVplPzDqbuSCd/3fXqYfakdOFToCWM69Upx85dPC0An+5mywQcn/br/fCprCVBCiDdvKPrMgQyxbz/CD8DZ6mK5U2TLA2uCryhMCImI8K/uF3aUIsd1Oo7NWOrWKKFgeX/mv1A+4fkMcA/Uw7rPE7ogUyG/VI5Shk5elrkt5kFJ8Xv6NLlFevkz3uiCCsja4O5fFCnpHumJ42iQiEo2cp1bwHJGhvxwnwY936XIWADbLkqQOPOhPT3Uc7aA6UvXw1KSu/qqKXVGQmG0/Nfwl6+CTkEzZ8zfc=}
