travis:
  secure:
    BINSTAR_TOKEN: fhS9RaksW9C7p2Rw+f47sjuEV4IWQBG8C5YYCfxAIMTBEpdLcAeDYJshjchdn7qpQf8J3vOidWGnDJ5EetWvW9sHfcahL3KKLYEqTqKV066lHQkGl5TfT+ehYimrOKP0XhS2Y472FF3WuTARkZKSGFduKNfbgwLIus0udST4oHPlO/mdnvRO73W0GeU+QxH/y7RTWhjUIFI7e+9LWlv3B3pyaoiwyIr8IXrgPlv3szq8ip36knaLs9EG47+NgZn2mltXgIn0fOW/b4ljaispw7hSCGBvSEuitU23d0aTwI5rFRDdIpWG7hkStLrBZTBZEH76Z7ZlLoza1TYElaZJO4tJVhpKQ5kF8ECXSr6usi3p4i3nmOTOr31uXiZKfpptiYGXKg4Ckc60QKyl8FXlVoCCWMn20KsNepwDhavf+nptqf7tpo+gb2BRZp5QsHxnNA7rOzeYb49YENdgMRSoI7YTXqf5uEB7I7cZTQijnyKHE4O6IyQlLVT5GoIBfNp7Kr6UuAK+hm//2scUXBXHOlapJMteD/pXJ1ma31VOnBaqX14f5fXjrnfxdfgVuLOcBXUfc6hmHPCjTghQL3MudgzXuztIAmB4RJAABg1N0NlnE1qGRh+xLwzsziN3MPUDO5ZwGYQv/WpLSMqar7aegl31D4YLkmQAml1Tx0WTlrM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4

osx_provider: circle
