azure:
  max_parallel: 25
  free_disk_space: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
